---
- name: Using Ansible to configure Arista's Ethernet Interfaces.
  hosts: arista

  tasks:
   - name: Setting up Ethernet6 description.
     eos_interface: name=Ethernet6 description="*** IN USE ***"
            eapi_username={{ eapi_username }}
            eapi_password={{ eapi_password }}
            eapi_hostname={{ eapi_hostname }}
            eapi_port={{ eapi_port }}

    
   - name: Set Ethernet6 to access mode, VLAN# 100
     eos_switchport: name=Ethernet6 mode=access access_vlan=100 trunk_allowed_vlans=all
            eapi_username={{ eapi_username }}
            eapi_password={{ eapi_password }}
            eapi_hostname={{ eapi_hostname }}
            eapi_port={{ eapi_port }} 
