---
- name: Testing Ansible Arista Configuration
  hosts: arista
  
  tasks:
   - name: Create VLANs on Arista Swicthes.
     eos_vlan: name={{item.name}} vlanid={{item.vlan_id}}
         eapi_username={{ eapi_username }}
         eapi_password={{ eapi_password }}
         eapi_hostname={{ eapi_hostname }}
         eapi_port={{ eapi_port }}
     with_items:
        - {name: BLUE, vlan_id: 100}
        - {name: RED, vlan_id: 200}
        - {name: GREEN, vlan_id: 300}
        
