---
test_routers:
  - {hostname: arista-rtr1, ip_addr: 1.1.1.1, DHCP: True, dhcp_network: 1.1.1.0 }
  - {hostname: arista-rtr2, ip_addr: 1.1.2.1, DHCP: True, dhcp_network: 1.1.2.0 }
  - {hostname: arista-rtr3, ip_addr: 1.1.3.1, DHCP: False, dhcp_network: none }
