switch_variables:
  - {hostname: EOS-1, ip_addr: 10.10.10.10, default_gateway: 10.10.10.1, snmp_community: public, access_vlan: 10, secret: password, SNMPv3: true }
  - {hostname: EOS-2, ip_addr: 10.20.20.20, default_gateway: 10.20.20.1, snmp_community: public, access_vlan: 20, secret: password, SNMPv3: false }
  - {hostname: EOS-3, ip_addr: 10.30.30.30, default_gateway: 10.30.30.1, snmp_community: public, access_vlan: 30, secret: password, SNMPv3: false }
  - {hostname: EOS-4, ip_addr: 10.40.40.40, default_gateway: 10.40.40.1, snmp_community: public, access_vlan: 40, secret: password, SNMPv3: true }
  - {hostname: EOS-5, ip_addr: 10.50.50.50, default_gateway: 10.50.50.1, snmp_community: public, access_vlan: 50, secret: password, SNMPv3: true }
