'''
Everytime I spin up a cloud server, I have to go through the painful process of installing each one of them. In order to overcome 
that hurdle, I have written an Ansible playbook that would create all of them in one go.

root@python-server:~# ansible-playbook package1.yml 

PLAY [local] ****************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Install Packages.] ***************************************************** 
ok: [localhost] => (item=nmap,traceroute,ruby)

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
'''



---
- hosts: local
  tasks:
    - name: Install Packages.
      apt: pkg={{ item }} state=installed update_cache=true
      with_items:
        - nmap
        - traceroute
        - ruby


