---
- hosts: local
  tasks:
    - name: Generate Configuration file.
      template: src=/root/router.j2 dest=/root/{{item.hostname}}.txt
      
      with_items:
       - {hostname: arista-rtr1, ip_addr: 1.1.1.1 }
       - {hostname: arista-rtr2, ip_addr: 1.1.1.2 }
       - {hostname: arista-rtr3, ip_addr: 1.1.1.3 }
       - {hostname: arista-rtr4, ip_addr: 1.1.1.4 }
